FROM golang:1.20-alpine as builder

RUN apk add git

WORKDIR /src

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 go build -o /server ./server

FROM scratch

COPY --from=builder /server /server

EXPOSE 8080

CMD ["/server"]